#!/usr/bin/env python3
"""
Daily Security Tool Generator
==============================
Called by GitHub Actions daily. Uses GitHub Models API (free) to generate a new CVE scanner,
writes it to the appropriate category folder, updates tools.json and README.md, and pushes.

Requires env var: GITHUB_TOKEN (automatically available in GitHub Actions)
"""

import ast
import json
import os
import re
import sys
import subprocess
from datetime import date
from pathlib import Path

from openai import OpenAI


# ── Category logic ────────────────────────────────────────────────────────────

CATEGORIES = {
    "rce":            lambda n: any(x in n for x in ["rce", "exec", "injection", "script_console", "jobserver"]),
    "ssrf":           lambda n: "ssrf" in n,
    "auth-bypass":    lambda n: any(x in n for x in ["auth_bypass", "unauth"]),
    "path-traversal": lambda n: any(x in n for x in ["traversal", "path_traversal"]),
    "info-leak":      lambda n: any(x in n for x in ["exposure", "leak", "debug"]),
    "phishing":       lambda n: any(x in n for x in ["phish", "oauth"]),
}

TARGET_KEYWORDS = [
    "jenkins", "kubernetes", "kube", "gitlab", "vault", "terraform", "grafana",
    "nexus", "keycloak", "ansible", "teamcity", "rabbitmq", "django", "flask",
    "spark", "consul", "harbor", "nginx", "struts", "argocd", "jupyter",
    "cassandra", "vite", "tomcat", "nextjs", "aws", "caddy", "gitlens",
]

def get_category(tool_name: str) -> str:
    n = tool_name.lower()
    for cat, fn in CATEGORIES.items():
        if fn(n):
            return cat
    return "misc"


# ── Helpers ───────────────────────────────────────────────────────────────────

def run(cmd: list[str], **kwargs) -> subprocess.CompletedProcess:
    return subprocess.run(cmd, check=True, text=True, capture_output=True, **kwargs)


def get_existing_tools() -> str:
    result = run(["git", "ls-files"])
    return result.stdout.strip()


def get_style_reference() -> str:
    for p in Path(".").rglob("*.py"):
        if p.parts[0] in ("rce", "ssrf", "auth-bypass", "path-traversal", "info-leak", "phishing", "misc", "scripts"):
            text = p.read_text(errors="replace")
            if "httpx" in text and "asyncio" in text and len(text) > 3000:
                return text[:4000]
    return ""


def load_tools_index() -> list:
    p = Path("tools.json")
    if p.exists():
        return json.loads(p.read_text())
    return []


def save_tools_index(tools: list):
    Path("tools.json").write_text(json.dumps(tools, indent=2))


# ── GitHub Models API call ────────────────────────────────────────────────────

SYSTEM_PROMPT = """\
You are a professional security researcher building a public library of CVE scanners
for authorized bug bounty and red team use. You write production-quality, well-documented
async Python tools. Your code is thorough, safe, and matches the style shown.

CRITICAL RULES — failure to follow these will invalidate the output:
- NEVER mention AI, Claude, GPT, LLM, or any AI tool anywhere in the code, comments, docstrings, or README.
- NEVER add "Generated by", "Created by AI", or any automation disclaimer.
- Write as if you are the human security researcher who discovered and coded this yourself.
- Use first-person researcher voice in docstrings and README (e.g. "I tested this against...", "This scanner checks...").
"""

USER_PROMPT_TEMPLATE = """\
Today's date: {today}

## Existing tools in the repo (do NOT duplicate these):
{existing_tools}

## Style reference -- match this structure and quality exactly:
```python
{style_ref}
```

---

Create a NEW security scanner for a **high-impact, currently relevant CVE or vulnerability
class** that is useful for bug bounty / red team. Requirements:

**Target categories** (pick one):
- Popular dev/ops tools (CI/CD, workflow engines, container orchestration, cloud CLIs)
- Web frameworks and runtime environments
- Authentication/SSO systems
- APIs and management panels

**Vulnerability classes** (pick one):
- Remote code execution (RCE)
- Authentication bypass
- Server-side request forgery (SSRF)
- Path/directory traversal
- Insecure deserialization
- SQL injection or command injection

**Technical requirements:**
- Async Python 3.10+ using httpx and asyncio
- Fingerprinting logic to detect the target software
- Version extraction and comparison against patched version
- Active probing (with --safe flag to skip probes and do detection-only)
- CLI flags: --target, --list, --output, --safe, --concurrency, --no-verify
- ANSI color terminal output: CRITICAL=red, HIGH=yellow, INFO=green, RESET
- JSON output with --output file.json
- Detailed module docstring with CVE info, usage examples, and references
- 350-550 lines total

**Format your response EXACTLY like this -- nothing before TOOL_NAME, nothing after the README block:**

TOOL_NAME: <snake_case_name_no_extension>
CVE: <CVE-YYYY-NNNNN or MULTI or N/A>
DESCRIPTION: <concise one-line description for the README log>
PYTHON_CODE:
```python
<complete scanner code>
```
README_CONTENT:
```markdown
<complete README.md for this tool>
```
"""


MAX_RETRIES = 3


def _parse_response(text: str) -> dict | None:
    tool_name_m   = re.search(r"TOOL_NAME:\s*(.+)", text)
    description_m = re.search(r"DESCRIPTION:\s*(.+)", text)
    python_m      = re.search(r"PYTHON_CODE:\s*```python\n(.*?)```", text, re.DOTALL)
    readme_m      = re.search(r"README_CONTENT:\s*```markdown\n(.*?)```", text, re.DOTALL)

    if not (tool_name_m and python_m and readme_m):
        return None

    return {
        "tool_name":   tool_name_m.group(1).strip().replace(" ", "_").lower(),
        "description": description_m.group(1).strip() if description_m else "Security scanner",
        "python_code": python_m.group(1),
        "readme":      readme_m.group(1),
    }


def call_model(today: str, existing_tools: str, style_ref: str) -> dict:
    client = OpenAI(
        base_url="https://models.inference.ai.azure.com",
        api_key=os.environ["GITHUB_TOKEN"],
    )

    prompt = USER_PROMPT_TEMPLATE.format(
        today=today,
        existing_tools=existing_tools,
        style_ref=style_ref,
    )

    for attempt in range(1, MAX_RETRIES + 1):
        print(f"[*] Calling GitHub Models API (gpt-4o) — attempt {attempt}/{MAX_RETRIES}...")
        response = client.chat.completions.create(
            model="gpt-4o",
            max_tokens=16384,
            messages=[
                {"role": "system", "content": SYSTEM_PROMPT},
                {"role": "user", "content": prompt},
            ],
        )

        finish_reason = response.choices[0].finish_reason
        text = response.choices[0].message.content

        if finish_reason == "length":
            print(f"[!] Response truncated (finish_reason=length) on attempt {attempt}.")
            if attempt < MAX_RETRIES:
                print("[*] Retrying...")
                continue

        result = _parse_response(text)
        if not result:
            print(f"[!] Response missing required sections on attempt {attempt}.")
            print("--- Response preview (first 800 chars) ---")
            print(text[:800])
            if attempt < MAX_RETRIES:
                print("[*] Retrying...")
            continue

        try:
            ast.parse(result["python_code"])
        except SyntaxError as e:
            print(f"[!] Generated code has a syntax error on attempt {attempt}: {e}")
            if attempt < MAX_RETRIES:
                print("[*] Retrying...")
            continue

        return result

    print("[!] All attempts failed. Exiting.")
    sys.exit(1)


# ── File writing & index updates ──────────────────────────────────────────────

def update_tools_json(today: str, tool_name: str, description: str,
                      category: str, cve: str | None, cvss: float | None, targets: list[str]):
    tools = load_tools_index()

    # Skip if today's tool is already indexed
    if any(t["date"] == today for t in tools):
        print("[*] tools.json already has today's entry, skipping.")
        return

    entry = {
        "name":        tool_name,
        "filename":    f"{tool_name}.py",
        "category":    category,
        "path":        f"{category}/{tool_name}.py",
        "date":        today,
        "cve":         cve,
        "cvss":        cvss,
        "description": description,
        "targets":     targets,
    }
    tools.insert(0, entry)
    save_tools_index(tools)
    print(f"[*] Updated tools.json ({len(tools)} tools)")


def update_root_readme(today: str, tool_name: str, description: str,
                       category: str, cve: str = "—"):
    readme = Path("README.md")
    content = readme.read_text()

    if f"{category}/{tool_name}.py" in content:
        print("[*] README.md already has this entry, skipping.")
        return

    new_row = f"| {today} | [{tool_name}.py]({category}/{tool_name}.py) | {cve} | {category} | {description} |"
    separator = "|------|------|-----|----------|-------------|"
    if separator in content:
        content = content.replace(separator, separator + "\n" + new_row, 1)
    else:
        content = content.rstrip() + f"\n{new_row}\n"

    readme.write_text(content)
    print("[*] Updated README.md")


def git_commit_and_push(category: str, tool_name: str, today: str):
    run(["git", "config", "user.name",  "thecosmicexplorer"])
    run(["git", "config", "user.email", "120761069+thecosmicexplorer@users.noreply.github.com"])
    run(["git", "add", category, "tools.json", "README.md"])
    run(["git", "commit", "-m", f"feat({category}): add {tool_name} ({today})"])
    run(["git", "push"])
    print(f"[+] Pushed {category}/{tool_name}.py to origin")


# ── Main ──────────────────────────────────────────────────────────────────────

def main():
    today = date.today().isoformat()

    # Idempotency check via tools.json
    tools = load_tools_index()
    if any(t["date"] == today for t in tools):
        print(f"[*] Tool for {today} already exists in tools.json -- nothing to do.")
        sys.exit(0)

    existing_tools = get_existing_tools()
    style_ref = get_style_reference()

    result = call_model(today, existing_tools, style_ref)
    tool_name = result["tool_name"]
    code      = result["python_code"]

    print(f"[*] Generated tool: {tool_name}")

    # Derive metadata from generated code
    cve_m  = re.search(r"(CVE-\d{4}-\d+)", code)
    cvss_m = re.search(r"CVSS[:\s]+(\d+\.?\d*)", code)
    cve    = cve_m.group(1) if cve_m else None
    cvss   = float(cvss_m.group(1)) if cvss_m else None
    cve_display = f"{cve} (CVSS {cvss})" if (cve and cvss) else (cve or "—")
    targets = [k for k in TARGET_KEYWORDS if k in tool_name.lower()]
    category = get_category(tool_name)

    # Write to category folder
    cat_dir = Path(category)
    cat_dir.mkdir(exist_ok=True)

    py_path = cat_dir / f"{tool_name}.py"
    py_path.write_text(code)
    print(f"[*] Written: {py_path}")

    # Per-tool README inside the category folder
    tool_readme = cat_dir / f"{tool_name}.md"
    tool_readme.write_text(result["readme"])
    print(f"[*] Written: {tool_readme}")

    update_tools_json(today, tool_name, result["description"],
                      category, cve, cvss, targets)
    update_root_readme(today, tool_name, result["description"],
                       category, cve_display)
    git_commit_and_push(category, tool_name, today)

    print(f"\n[+] Done! Tool published: {category}/{tool_name}.py")


if __name__ == "__main__":
    main()
